# Generated by Django 4.2 on 2023-08-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('review', models.TextField()),
                ('number', models.TextField(unique=True)),
                ('registration_date', models.CharField(max_length=20)),
            ],
        ),
    ]
